name: aoneadmin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.4.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.71.0
  intl: ^0.20.2
  expansion_tile_group: ^2.2.0
  fluttertoast: ^8.0.9
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.2
  http: ^1.2.2
  dio: ^5.7.0
  firebase_messaging: ^15.1.0
  overlay_loader_with_app_icon: ^0.0.4
  shared_preferences: ^2.2.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png
    - assets/aipay_uat.html
    - assets/aipay_prod.html
